"""Add image_type column to images table

Revision ID: 4b50ae353818
Revises: 2a27bc06e2ad
Create Date: 2025-03-06 02:47:28.891399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b50ae353818'
down_revision = '2a27bc06e2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_type', sa.String(length=10), nullable=False))
        batch_op.alter_column('url',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('type')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=10), nullable=False))
        batch_op.alter_column('url',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('image_type')

    # ### end Alembic commands ###
